"""Initial migration

Revision ID: 49dd20c2f06d
Revises: 
Create Date: 2025-10-15 11:50:30.362244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49dd20c2f06d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('my_message_color', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('their_message_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'their_message_color')
    op.drop_column('chats', 'my_message_color')
    # ### end Alembic commands ###
